name: Daily Action

on:
  schedule:
    - cron: '45 12 * * *'  # Schedule daily at midnight

jobs:
  trigger-daily-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Trigger Daily Action
        run: |
          curl -X GET https://senantle.onrender.com/daily-action
